{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "asyncio\n",
    "\n",
    "# Futures\n",
    "\n",
    "**Source code:** `Lib/asyncio/futures.py`, `Lib/asyncio/base_futures.py`\n",
    "\n",
    "------------------------------------------------------------------------\n",
    "\n",
    "*Future* objects are used to bridge **low-level callback-based code**\n",
    "with high-level async/await code.\n",
    "\n",
    "## Future Functions\n",
    "\n",
    "isfuture(obj)\n",
    "\n",
    "Return `True` if *obj* is either of:\n",
    "\n",
    "-   an instance of `asyncio.Future`,\n",
    "-   an instance of `asyncio.Task`,\n",
    "-   a Future-like object with a `_asyncio_future_blocking` attribute.\n",
    "\n",
    "3.5\n",
    "\n",
    "ensure_future(obj, \\*, loop=None)\n",
    "\n",
    "Return:\n",
    "\n",
    "-   *obj* argument as is, if *obj* is a `Future`, a `Task`, or a\n",
    "    Future-like object (`isfuture` is used for the test.)\n",
    "-   a `Task` object wrapping *obj*, if *obj* is a coroutine\n",
    "    (`iscoroutine` is used for the test); in this case the coroutine\n",
    "    will be scheduled by `ensure_future()`.\n",
    "-   a `Task` object that would await on *obj*, if *obj* is an awaitable\n",
    "    (`inspect.isawaitable` is used for the test.)\n",
    "\n",
    "If *obj* is neither of the above a `TypeError` is raised.\n",
    "\n",
    "Important\n",
    "\n",
    "See also the `create_task` function which is the preferred way for\n",
    "creating new Tasks.\n",
    "\n",
    "Save a reference to the result of this function, to avoid a task\n",
    "disappearing mid execution.\n",
    "\n",
    "3.5.1 The function accepts any `awaitable` object.\n",
    "\n",
    "3.10 Deprecation warning is emitted if *obj* is not a Future-like object\n",
    "and *loop* is not specified and there is no running event loop.\n",
    "\n",
    "wrap_future(future, \\*, loop=None)\n",
    "\n",
    "Wrap a `concurrent.futures.Future` object in a `asyncio.Future` object.\n",
    "\n",
    "3.10 Deprecation warning is emitted if *future* is not a Future-like\n",
    "object and *loop* is not specified and there is no running event loop.\n",
    "\n",
    "## Future Object\n",
    "\n",
    "A Future represents an eventual result of an asynchronous operation. Not\n",
    "thread-safe.\n",
    "\n",
    "Future is an `awaitable` object. Coroutines can await on Future objects\n",
    "until they either have a result or an exception set, or until they are\n",
    "cancelled.\n",
    "\n",
    "Typically Futures are used to enable low-level callback-based code (e.g.\n",
    "in protocols implemented using asyncio\n",
    "`transports <asyncio-transports-protocols>`) to interoperate with\n",
    "high-level async/await code.\n",
    "\n",
    "The rule of thumb is to never expose Future objects in user-facing APIs,\n",
    "and the recommended way to create a Future object is to call\n",
    "`loop.create_future`. This way alternative event loop implementations\n",
    "can inject their own optimized implementations of a Future object.\n",
    "\n",
    "3.7 Added support for the `contextvars` module.\n",
    "\n",
    "3.10 Deprecation warning is emitted if *loop* is not specified and there\n",
    "is no running event loop.\n",
    "\n",
    "result()\n",
    "\n",
    "Return the result of the Future.\n",
    "\n",
    "If the Future is *done* and has a result set by the `set_result` method,\n",
    "the result value is returned.\n",
    "\n",
    "If the Future is *done* and has an exception set by the `set_exception`\n",
    "method, this method raises the exception.\n",
    "\n",
    "If the Future has been *cancelled*, this method raises a\n",
    "`CancelledError` exception.\n",
    "\n",
    "If the Future's result isn't yet available, this method raises a\n",
    "`InvalidStateError` exception.\n",
    "\n",
    "set_result(result)\n",
    "\n",
    "Mark the Future as *done* and set its result.\n",
    "\n",
    "Raises a `InvalidStateError` error if the Future is already *done*.\n",
    "\n",
    "set_exception(exception)\n",
    "\n",
    "Mark the Future as *done* and set an exception.\n",
    "\n",
    "Raises a `InvalidStateError` error if the Future is already *done*.\n",
    "\n",
    "done()\n",
    "\n",
    "Return `True` if the Future is *done*.\n",
    "\n",
    "A Future is *done* if it was *cancelled* or if it has a result or an\n",
    "exception set with `set_result` or `set_exception` calls.\n",
    "\n",
    "cancelled()\n",
    "\n",
    "Return `True` if the Future was *cancelled*.\n",
    "\n",
    "The method is usually used to check if a Future is not *cancelled*\n",
    "before setting a result or an exception for it:\n",
    "\n",
    "    if not fut.cancelled():\n",
    "        fut.set_result(42)\n",
    "\n",
    "add_done_callback(callback, \\*, context=None)\n",
    "\n",
    "Add a callback to be run when the Future is *done*.\n",
    "\n",
    "The *callback* is called with the Future object as its only argument.\n",
    "\n",
    "If the Future is already *done* when this method is called, the callback\n",
    "is scheduled with `loop.call_soon`.\n",
    "\n",
    "An optional keyword-only *context* argument allows specifying a custom\n",
    "`contextvars.Context` for the *callback* to run in. The current context\n",
    "is used when no *context* is provided.\n",
    "\n",
    "`functools.partial` can be used to pass parameters to the callback,\n",
    "e.g.:\n",
    "\n",
    "    # Call 'print(\"Future:\", fut)' when \"fut\" is done.\n",
    "    fut.add_done_callback(\n",
    "        functools.partial(print, \"Future:\"))\n",
    "\n",
    "3.7 The *context* keyword-only parameter was added. See `567` for more\n",
    "details.\n",
    "\n",
    "remove_done_callback(callback)\n",
    "\n",
    "Remove *callback* from the callbacks list.\n",
    "\n",
    "Returns the number of callbacks removed, which is typically 1, unless a\n",
    "callback was added more than once.\n",
    "\n",
    "cancel(msg=None)\n",
    "\n",
    "Cancel the Future and schedule callbacks.\n",
    "\n",
    "If the Future is already *done* or *cancelled*, return `False`.\n",
    "Otherwise, change the Future's state to *cancelled*, schedule the\n",
    "callbacks, and return `True`.\n",
    "\n",
    "3.9 Added the *msg* parameter.\n",
    "\n",
    "3.11 3.14 *msg* parameter is ambiguous when multiple `cancel` are called\n",
    "with different cancellation messages. The argument will be removed.\n",
    "\n",
    "exception()\n",
    "\n",
    "Return the exception that was set on this Future.\n",
    "\n",
    "The exception (or `None` if no exception was set) is returned only if\n",
    "the Future is *done*.\n",
    "\n",
    "If the Future has been *cancelled*, this method raises a\n",
    "`CancelledError` exception.\n",
    "\n",
    "If the Future isn't *done* yet, this method raises an\n",
    "`InvalidStateError` exception.\n",
    "\n",
    "get_loop()\n",
    "\n",
    "Return the event loop the Future object is bound to.\n",
    "\n",
    "3.7\n",
    "\n",
    "This example creates a Future object, creates and schedules an\n",
    "asynchronous Task to set result for the Future, and waits until the\n",
    "Future has a result:\n",
    "\n",
    "    async def set_after(fut, delay, value):\n",
    "        # Sleep for *delay* seconds.\n",
    "        await asyncio.sleep(delay)\n",
    "\n",
    "        # Set *value* as a result of *fut* Future.\n",
    "        fut.set_result(value)\n",
    "\n",
    "    async def main():\n",
    "        # Get the current event loop.\n",
    "        loop = asyncio.get_running_loop()\n",
    "\n",
    "        # Create a new Future object.\n",
    "        fut = loop.create_future()\n",
    "\n",
    "        # Run \"set_after()\" coroutine in a parallel Task.\n",
    "        # We are using the low-level \"loop.create_task()\" API here because\n",
    "        # we already have a reference to the event loop at hand.\n",
    "        # Otherwise we could have just used \"asyncio.create_task()\".\n",
    "        loop.create_task(\n",
    "            set_after(fut, 1, '... world'))\n",
    "\n",
    "        print('hello ...')\n",
    "\n",
    "        # Wait until *fut* has a result (1 second) and print it.\n",
    "        print(await fut)\n",
    "\n",
    "    asyncio.run(main())\n",
    "\n",
    "Important\n",
    "\n",
    "The Future object was designed to mimic `concurrent.futures.Future`. Key\n",
    "differences include:\n",
    "\n",
    "-   unlike asyncio Futures, `concurrent.futures.Future` instances cannot\n",
    "    be awaited.\n",
    "\n",
    "-   `asyncio.Future.result` and `asyncio.Future.exception` do not accept\n",
    "    the *timeout* argument.\n",
    "\n",
    "-   `asyncio.Future.result` and `asyncio.Future.exception` raise an\n",
    "    `InvalidStateError` exception when the Future is not *done*.\n",
    "\n",
    "-   Callbacks registered with `asyncio.Future.add_done_callback` are not\n",
    "    called immediately. They are scheduled with `loop.call_soon`\n",
    "    instead.\n",
    "\n",
    "-   asyncio Future is not compatible with the `concurrent.futures.wait`\n",
    "    and `concurrent.futures.as_completed` functions.\n",
    "\n",
    "-   `asyncio.Future.cancel` accepts an optional `msg` argument, but\n",
    "    `concurrent.futures.cancel` does not.\n",
    "\n",
    "    3.11 3.14 *msg* parameter is ambiguous when multiple `cancel` are\n",
    "    called with different cancellation messages. The argument will be\n",
    "    removed."
   ],
   "id": "ee936f97-1f7a-4992-b255-37b8016b9b8b"
  }
 ],
 "nbformat": 4,
 "nbformat_minor": 5,
 "metadata": {}
}
