{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Python Development Mode\n",
    "\n",
    "3.7\n",
    "\n",
    "The Python Development Mode introduces additional runtime checks that\n",
    "are too expensive to be enabled by default. It should not be more\n",
    "verbose than the default if the code is correct; new warnings are only\n",
    "emitted when an issue is detected.\n",
    "\n",
    "It can be enabled using the `-X dev <-X>` command line option or by\n",
    "setting the `PYTHONDEVMODE` environment variable to `1`.\n",
    "\n",
    "See also `Python debug build <debug-build>`.\n",
    "\n",
    "# Effects of the Python Development Mode\n",
    "\n",
    "Enabling the Python Development Mode is similar to the following\n",
    "command, but with additional effects described below:\n",
    "\n",
    "    PYTHONMALLOC=debug PYTHONASYNCIODEBUG=1 python3 -W default -X faulthandler\n",
    "\n",
    "Effects of the Python Development Mode:\n",
    "\n",
    "-   Add `default` `warning filter <describing-warning-filters>`. The\n",
    "    following warnings are shown:\n",
    "\n",
    "    -   `DeprecationWarning`\n",
    "    -   `ImportWarning`\n",
    "    -   `PendingDeprecationWarning`\n",
    "    -   `ResourceWarning`\n",
    "\n",
    "    Normally, the above warnings are filtered by the default `warning\n",
    "    filters <describing-warning-filters>`.\n",
    "\n",
    "    It behaves as if the `-W default <-W>` command line option is used.\n",
    "\n",
    "    Use the `-W error <-W>` command line option or set the\n",
    "    `PYTHONWARNINGS` environment variable to `error` to treat warnings\n",
    "    as errors.\n",
    "\n",
    "-   Install debug hooks on memory allocators to check for:\n",
    "\n",
    "    -   Buffer underflow\n",
    "    -   Buffer overflow\n",
    "    -   Memory allocator API violation\n",
    "    -   Unsafe usage of the GIL\n",
    "\n",
    "    See the :c`PyMem_SetupDebugHooks` C function.\n",
    "\n",
    "    It behaves as if the `PYTHONMALLOC` environment variable is set to\n",
    "    `debug`.\n",
    "\n",
    "    To enable the Python Development Mode without installing debug hooks\n",
    "    on memory allocators, set the `PYTHONMALLOC` environment variable to\n",
    "    `default`.\n",
    "\n",
    "-   Call `faulthandler.enable` at Python startup to install handlers for\n",
    "    the `SIGSEGV`, `SIGFPE`, `SIGABRT`, `SIGBUS` and `SIGILL` signals to\n",
    "    dump the Python traceback on a crash.\n",
    "\n",
    "    It behaves as if the `-X faulthandler <-X>` command line option is\n",
    "    used or if the `PYTHONFAULTHANDLER` environment variable is set to\n",
    "    `1`.\n",
    "\n",
    "-   Enable `asyncio debug mode <asyncio-debug-mode>`. For example,\n",
    "    `asyncio` checks for coroutines that were not awaited and logs them.\n",
    "\n",
    "    It behaves as if the `PYTHONASYNCIODEBUG` environment variable is\n",
    "    set to `1`.\n",
    "\n",
    "-   Check the *encoding* and *errors* arguments for string encoding and\n",
    "    decoding operations. Examples: `open`, `str.encode` and\n",
    "    `bytes.decode`.\n",
    "\n",
    "    By default, for best performance, the *errors* argument is only\n",
    "    checked at the first encoding/decoding error and the *encoding*\n",
    "    argument is sometimes ignored for empty strings.\n",
    "\n",
    "-   The `io.IOBase` destructor logs `close()` exceptions.\n",
    "\n",
    "-   Set the `~sys.flags.dev_mode` attribute of `sys.flags` to `True`.\n",
    "\n",
    "The Python Development Mode does not enable the `tracemalloc` module by\n",
    "default, because the overhead cost (to performance and memory) would be\n",
    "too large. Enabling the `tracemalloc` module provides additional\n",
    "information on the origin of some errors. For example, `ResourceWarning`\n",
    "logs the traceback where the resource was allocated, and a buffer\n",
    "overflow error logs the traceback where the memory block was allocated.\n",
    "\n",
    "The Python Development Mode does not prevent the `-O` command line\n",
    "option from removing `assert` statements nor from setting `__debug__` to\n",
    "`False`.\n",
    "\n",
    "The Python Development Mode can only be enabled at the Python startup.\n",
    "Its value can be read from `sys.flags.dev_mode <sys.flags>`.\n",
    "\n",
    "3.8 The `io.IOBase` destructor now logs `close()` exceptions.\n",
    "\n",
    "3.9 The *encoding* and *errors* arguments are now checked for string\n",
    "encoding and decoding operations.\n",
    "\n",
    "# ResourceWarning Example\n",
    "\n",
    "Example of a script counting the number of lines of the text file\n",
    "specified in the command line:\n",
    "\n",
    "    import sys\n",
    "\n",
    "    def main():\n",
    "        fp = open(sys.argv[1])\n",
    "        nlines = len(fp.readlines())\n",
    "        print(nlines)\n",
    "        # The file is closed implicitly\n",
    "\n",
    "    if __name__ == \"__main__\":\n",
    "        main()\n",
    "\n",
    "The script does not close the file explicitly. By default, Python does\n",
    "not emit any warning. Example using README.txt, which has 269 lines:\n",
    "\n",
    "``` shell-session\n",
    "$ python3 script.py README.txt\n",
    "269\n",
    "```\n",
    "\n",
    "Enabling the Python Development Mode displays a `ResourceWarning`\n",
    "warning:\n",
    "\n",
    "``` shell-session\n",
    "$ python3 -X dev script.py README.txt\n",
    "269\n",
    "script.py:10: ResourceWarning: unclosed file <_io.TextIOWrapper name='README.rst' mode='r' encoding='UTF-8'>\n",
    "  main()\n",
    "ResourceWarning: Enable tracemalloc to get the object allocation traceback\n",
    "```\n",
    "\n",
    "In addition, enabling `tracemalloc` shows the line where the file was\n",
    "opened:\n",
    "\n",
    "``` shell-session\n",
    "$ python3 -X dev -X tracemalloc=5 script.py README.rst\n",
    "269\n",
    "script.py:10: ResourceWarning: unclosed file <_io.TextIOWrapper name='README.rst' mode='r' encoding='UTF-8'>\n",
    "  main()\n",
    "Object allocated at (most recent call last):\n",
    "  File \"script.py\", lineno 10\n",
    "    main()\n",
    "  File \"script.py\", lineno 4\n",
    "    fp = open(sys.argv[1])\n",
    "```\n",
    "\n",
    "The fix is to close explicitly the file. Example using a context\n",
    "manager:\n",
    "\n",
    "    def main():\n",
    "        # Close the file explicitly when exiting the with block\n",
    "        with open(sys.argv[1]) as fp:\n",
    "            nlines = len(fp.readlines())\n",
    "        print(nlines)\n",
    "\n",
    "Not closing a resource explicitly can leave a resource open for way\n",
    "longer than expected; it can cause severe issues upon exiting Python. It\n",
    "is bad in CPython, but it is even worse in PyPy. Closing resources\n",
    "explicitly makes an application more deterministic and more reliable.\n",
    "\n",
    "# Bad file descriptor error example\n",
    "\n",
    "Script displaying the first line of itself:\n",
    "\n",
    "    import os\n",
    "\n",
    "    def main():\n",
    "        fp = open(__file__)\n",
    "        firstline = fp.readline()\n",
    "        print(firstline.rstrip())\n",
    "        os.close(fp.fileno())\n",
    "        # The file is closed implicitly\n",
    "\n",
    "    main()\n",
    "\n",
    "By default, Python does not emit any warning:\n",
    "\n",
    "``` shell-session\n",
    "$ python3 script.py\n",
    "import os\n",
    "```\n",
    "\n",
    "The Python Development Mode shows a `ResourceWarning` and logs a \"Bad\n",
    "file descriptor\" error when finalizing the file object:\n",
    "\n",
    "``` shell-session\n",
    "$ python3 script.py\n",
    "import os\n",
    "script.py:10: ResourceWarning: unclosed file <_io.TextIOWrapper name='script.py' mode='r' encoding='UTF-8'>\n",
    "  main()\n",
    "ResourceWarning: Enable tracemalloc to get the object allocation traceback\n",
    "Exception ignored in: <_io.TextIOWrapper name='script.py' mode='r' encoding='UTF-8'>\n",
    "Traceback (most recent call last):\n",
    "  File \"script.py\", line 10, in <module>\n",
    "    main()\n",
    "OSError: [Errno 9] Bad file descriptor\n",
    "```\n",
    "\n",
    "`os.close(fp.fileno())` closes the file descriptor. When the file object\n",
    "finalizer tries to close the file descriptor again, it fails with the\n",
    "`Bad file descriptor` error. A file descriptor must be closed only once.\n",
    "In the worst case scenario, closing it twice can lead to a crash (see\n",
    "`18748` for an example).\n",
    "\n",
    "The fix is to remove the `os.close(fp.fileno())` line, or open the file\n",
    "with `closefd=False`."
   ],
   "id": "d97bc156-7e06-4a9a-b955-0ffcc923ab35"
  }
 ],
 "nbformat": 4,
 "nbformat_minor": 5,
 "metadata": {}
}
