{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Built-in Exceptions\n",
    "\n",
    "statement: try statement: except\n",
    "\n",
    "In Python, all exceptions must be instances of a class that derives from\n",
    "`BaseException`. In a `try` statement with an `except` clause that\n",
    "mentions a particular class, that clause also handles any exception\n",
    "classes derived from that class (but not exception classes from which\n",
    "*it* is derived). Two exception classes that are not related via\n",
    "subclassing are never equivalent, even if they have the same name.\n",
    "\n",
    "statement: raise\n",
    "\n",
    "The built-in exceptions listed below can be generated by the interpreter\n",
    "or built-in functions. Except where mentioned, they have an \"associated\n",
    "value\" indicating the detailed cause of the error. This may be a string\n",
    "or a tuple of several items of information (e.g., an error code and a\n",
    "string explaining the code). The associated value is usually passed as\n",
    "arguments to the exception class's constructor.\n",
    "\n",
    "User code can raise built-in exceptions. This can be used to test an\n",
    "exception handler or to report an error condition \"just like\" the\n",
    "situation in which the interpreter raises the same exception; but beware\n",
    "that there is nothing to prevent user code from raising an inappropriate\n",
    "error.\n",
    "\n",
    "The built-in exception classes can be subclassed to define new\n",
    "exceptions; programmers are encouraged to derive new exceptions from the\n",
    "`Exception` class or one of its subclasses, and not from\n",
    "`BaseException`. More information on defining exceptions is available in\n",
    "the Python Tutorial under `tut-userexceptions`.\n",
    "\n",
    "## Exception context\n",
    "\n",
    "When raising a new exception while another exception is already being\n",
    "handled, the new exception's `__context__` attribute is automatically\n",
    "set to the handled exception. An exception may be handled when an\n",
    "`except` or `finally` clause, or a `with` statement, is used.\n",
    "\n",
    "This implicit exception context can be supplemented with an explicit\n",
    "cause by using `!from` with `raise`:\n",
    "\n",
    "    raise new_exc from original_exc\n",
    "\n",
    "The expression following `from<raise>` must be an exception or `None`.\n",
    "It will be set as `__cause__` on the raised exception. Setting\n",
    "`__cause__` also implicitly sets the `__suppress_context__` attribute to\n",
    "`True`, so that using `raise new_exc from None` effectively replaces the\n",
    "old exception with the new one for display purposes (e.g. converting\n",
    "`KeyError` to `AttributeError`), while leaving the old exception\n",
    "available in `__context__` for introspection when debugging.\n",
    "\n",
    "The default traceback display code shows these chained exceptions in\n",
    "addition to the traceback for the exception itself. An explicitly\n",
    "chained exception in `__cause__` is always shown when present. An\n",
    "implicitly chained exception in `__context__` is shown only if\n",
    "`__cause__` is `None` and `__suppress_context__` is false.\n",
    "\n",
    "In either case, the exception itself is always shown after any chained\n",
    "exceptions so that the final line of the traceback always shows the last\n",
    "exception that was raised.\n",
    "\n",
    "## Inheriting from built-in exceptions\n",
    "\n",
    "User code can create subclasses that inherit from an exception type.\n",
    "It's recommended to only subclass one exception type at a time to avoid\n",
    "any possible conflicts between how the bases handle the `args`\n",
    "attribute, as well as due to possible memory layout incompatibilities.\n",
    "\n",
    "Most built-in exceptions are implemented in C for efficiency, see:\n",
    "`Objects/exceptions.c`. Some have custom memory layouts which makes it\n",
    "impossible to create a subclass that inherits from multiple exception\n",
    "types. The memory layout of a type is an implementation detail and might\n",
    "change between Python versions, leading to new conflicts in the future.\n",
    "Therefore, it's recommended to avoid subclassing multiple exception\n",
    "types altogether.\n",
    "\n",
    "## Base classes\n",
    "\n",
    "The following exceptions are used mostly as base classes for other\n",
    "exceptions.\n",
    "\n",
    "BaseException\n",
    "\n",
    "The base class for all built-in exceptions. It is not meant to be\n",
    "directly inherited by user-defined classes (for that, use `Exception`).\n",
    "If `str` is called on an instance of this class, the representation of\n",
    "the argument(s) to the instance are returned, or the empty string when\n",
    "there were no arguments.\n",
    "\n",
    "args\n",
    "\n",
    "The tuple of arguments given to the exception constructor. Some built-in\n",
    "exceptions (like `OSError`) expect a certain number of arguments and\n",
    "assign a special meaning to the elements of this tuple, while others are\n",
    "usually called only with a single string giving an error message.\n",
    "\n",
    "with_traceback(tb)\n",
    "\n",
    "This method sets *tb* as the new traceback for the exception and returns\n",
    "the exception object. It was more commonly used before the exception\n",
    "chaining features of `3134` became available. The following example\n",
    "shows how we can convert an instance of `SomeException` into an instance\n",
    "of `OtherException` while preserving the traceback. Once raised, the\n",
    "current frame is pushed onto the traceback of the `OtherException`, as\n",
    "would have happened to the traceback of the original `SomeException` had\n",
    "we allowed it to propagate to the caller. :\n",
    "\n",
    "    try:\n",
    "        ...\n",
    "    except SomeException:\n",
    "        tb = sys.exc_info()[2]\n",
    "        raise OtherException(...).with_traceback(tb)\n",
    "\n",
    "add_note(note)\n",
    "\n",
    "Add the string `note` to the exception's notes which appear in the\n",
    "standard traceback after the exception string. A `TypeError` is raised\n",
    "if `note` is not a string.\n",
    "\n",
    "3.11\n",
    "\n",
    "\\_\\_notes\\_\\_\n",
    "\n",
    "A list of the notes of this exception, which were added with `add_note`.\n",
    "This attribute is created when `add_note` is called.\n",
    "\n",
    "3.11\n",
    "\n",
    "Exception\n",
    "\n",
    "All built-in, non-system-exiting exceptions are derived from this class.\n",
    "All user-defined exceptions should also be derived from this class.\n",
    "\n",
    "ArithmeticError\n",
    "\n",
    "The base class for those built-in exceptions that are raised for various\n",
    "arithmetic errors: `OverflowError`, `ZeroDivisionError`,\n",
    "`FloatingPointError`.\n",
    "\n",
    "BufferError\n",
    "\n",
    "Raised when a `buffer <bufferobjects>` related operation cannot be\n",
    "performed.\n",
    "\n",
    "LookupError\n",
    "\n",
    "The base class for the exceptions that are raised when a key or index\n",
    "used on a mapping or sequence is invalid: `IndexError`, `KeyError`. This\n",
    "can be raised directly by `codecs.lookup`.\n",
    "\n",
    "## Concrete exceptions\n",
    "\n",
    "The following exceptions are the exceptions that are usually raised.\n",
    "\n",
    "AssertionError\n",
    "\n",
    "statement: assert\n",
    "\n",
    "Raised when an `assert` statement fails.\n",
    "\n",
    "AttributeError\n",
    "\n",
    "Raised when an attribute reference (see `attribute-references`) or\n",
    "assignment fails. (When an object does not support attribute references\n",
    "or attribute assignments at all, `TypeError` is raised.)\n",
    "\n",
    "The `name` and `obj` attributes can be set using keyword-only arguments\n",
    "to the constructor. When set they represent the name of the attribute\n",
    "that was attempted to be accessed and the object that was accessed for\n",
    "said attribute, respectively.\n",
    "\n",
    "3.10 Added the `name` and `obj` attributes.\n",
    "\n",
    "EOFError\n",
    "\n",
    "Raised when the `input` function hits an end-of-file condition (EOF)\n",
    "without reading any data. (N.B.: the `io.IOBase.read` and\n",
    "`io.IOBase.readline` methods return an empty string when they hit EOF.)\n",
    "\n",
    "FloatingPointError\n",
    "\n",
    "Not currently used.\n",
    "\n",
    "GeneratorExit\n",
    "\n",
    "Raised when a `generator` or `coroutine` is closed; see\n",
    "`generator.close` and `coroutine.close`. It directly inherits from\n",
    "`BaseException` instead of `Exception` since it is technically not an\n",
    "error.\n",
    "\n",
    "ImportError\n",
    "\n",
    "Raised when the `import` statement has troubles trying to load a module.\n",
    "Also raised when the \"from list\" in `from ... import` has a name that\n",
    "cannot be found.\n",
    "\n",
    "The `name` and `path` attributes can be set using keyword-only arguments\n",
    "to the constructor. When set they represent the name of the module that\n",
    "was attempted to be imported and the path to any file which triggered\n",
    "the exception, respectively.\n",
    "\n",
    "3.3 Added the `name` and `path` attributes.\n",
    "\n",
    "ModuleNotFoundError\n",
    "\n",
    "A subclass of `ImportError` which is raised by `import` when a module\n",
    "could not be located. It is also raised when `None` is found in\n",
    "`sys.modules`.\n",
    "\n",
    "3.6\n",
    "\n",
    "IndexError\n",
    "\n",
    "Raised when a sequence subscript is out of range. (Slice indices are\n",
    "silently truncated to fall in the allowed range; if an index is not an\n",
    "integer, `TypeError` is raised.)\n",
    "\n",
    "KeyError\n",
    "\n",
    "Raised when a mapping (dictionary) key is not found in the set of\n",
    "existing keys.\n",
    "\n",
    "KeyboardInterrupt\n",
    "\n",
    "Raised when the user hits the interrupt key (normally `Control-C` or\n",
    "`Delete`). During execution, a check for interrupts is made regularly.\n",
    "The exception inherits from `BaseException` so as to not be accidentally\n",
    "caught by code that catches `Exception` and thus prevent the interpreter\n",
    "from exiting.\n",
    "\n",
    "Note\n",
    "\n",
    "Catching a `KeyboardInterrupt` requires special consideration. Because\n",
    "it can be raised at unpredictable points, it may, in some circumstances,\n",
    "leave the running program in an inconsistent state. It is generally best\n",
    "to allow `KeyboardInterrupt` to end the program as quickly as possible\n",
    "or avoid raising it entirely. (See `handlers-and-exceptions`.)\n",
    "\n",
    "MemoryError\n",
    "\n",
    "Raised when an operation runs out of memory but the situation may still\n",
    "be rescued (by deleting some objects). The associated value is a string\n",
    "indicating what kind of (internal) operation ran out of memory. Note\n",
    "that because of the underlying memory management architecture (C's\n",
    ":c`malloc` function), the interpreter may not always be able to\n",
    "completely recover from this situation; it nevertheless raises an\n",
    "exception so that a stack traceback can be printed, in case a run-away\n",
    "program was the cause.\n",
    "\n",
    "NameError\n",
    "\n",
    "Raised when a local or global name is not found. This applies only to\n",
    "unqualified names. The associated value is an error message that\n",
    "includes the name that could not be found.\n",
    "\n",
    "The `name` attribute can be set using a keyword-only argument to the\n",
    "constructor. When set it represent the name of the variable that was\n",
    "attempted to be accessed.\n",
    "\n",
    "3.10 Added the `name` attribute.\n",
    "\n",
    "NotImplementedError\n",
    "\n",
    "This exception is derived from `RuntimeError`. In user defined base\n",
    "classes, abstract methods should raise this exception when they require\n",
    "derived classes to override the method, or while the class is being\n",
    "developed to indicate that the real implementation still needs to be\n",
    "added.\n",
    "\n",
    "Note\n",
    "\n",
    "It should not be used to indicate that an operator or method is not\n",
    "meant to be supported at all -- in that case either leave the operator /\n",
    "method undefined or, if a subclass, set it to `None`.\n",
    "\n",
    "Note\n",
    "\n",
    "`NotImplementedError` and `NotImplemented` are not interchangeable, even\n",
    "though they have similar names and purposes. See `NotImplemented` for\n",
    "details on when to use it.\n",
    "\n",
    "OSError(\\[arg\\]) OSError(errno, strerror\\[, filename\\[, winerror\\[,\n",
    "filename2\\]\\]\\])\n",
    "\n",
    "module: errno\n",
    "\n",
    "This exception is raised when a system function returns a system-related\n",
    "error, including I/O failures such as \"file not found\" or \"disk full\"\n",
    "(not for illegal argument types or other incidental errors).\n",
    "\n",
    "The second form of the constructor sets the corresponding attributes,\n",
    "described below. The attributes default to `None` if not specified. For\n",
    "backwards compatibility, if three arguments are passed, the\n",
    "`~BaseException.args` attribute contains only a 2-tuple of the first two\n",
    "constructor arguments.\n",
    "\n",
    "The constructor often actually returns a subclass of `OSError`, as\n",
    "described in [OS exceptions](#os-exceptions) below. The particular\n",
    "subclass depends on the final `.errno` value. This behaviour only occurs\n",
    "when constructing `OSError` directly or via an alias, and is not\n",
    "inherited when subclassing.\n",
    "\n",
    "errno\n",
    "\n",
    "A numeric error code from the C variable :c`errno`.\n",
    "\n",
    "winerror\n",
    "\n",
    "Under Windows, this gives you the native Windows error code. The\n",
    "`.errno` attribute is then an approximate translation, in POSIX terms,\n",
    "of that native error code.\n",
    "\n",
    "Under Windows, if the *winerror* constructor argument is an integer, the\n",
    "`.errno` attribute is determined from the Windows error code, and the\n",
    "*errno* argument is ignored. On other platforms, the *winerror* argument\n",
    "is ignored, and the `winerror` attribute does not exist.\n",
    "\n",
    "strerror\n",
    "\n",
    "The corresponding error message, as provided by the operating system. It\n",
    "is formatted by the C functions :c`perror` under POSIX, and\n",
    ":c`FormatMessage` under Windows.\n",
    "\n",
    "filename filename2\n",
    "\n",
    "For exceptions that involve a file system path (such as `open` or\n",
    "`os.unlink`), `filename` is the file name passed to the function. For\n",
    "functions that involve two file system paths (such as `os.rename`),\n",
    "`filename2` corresponds to the second file name passed to the function.\n",
    "\n",
    "3.3 `EnvironmentError`, `IOError`, `WindowsError`, `socket.error`,\n",
    "`select.error` and `mmap.error` have been merged into `OSError`, and the\n",
    "constructor may return a subclass.\n",
    "\n",
    "3.4 The `filename` attribute is now the original file name passed to the\n",
    "function, instead of the name encoded to or decoded from the\n",
    "`filesystem encoding and error handler`. Also, the *filename2*\n",
    "constructor argument and attribute was added.\n",
    "\n",
    "OverflowError\n",
    "\n",
    "Raised when the result of an arithmetic operation is too large to be\n",
    "represented. This cannot occur for integers (which would rather raise\n",
    "`MemoryError` than give up). However, for historical reasons,\n",
    "OverflowError is sometimes raised for integers that are outside a\n",
    "required range. Because of the lack of standardization of floating point\n",
    "exception handling in C, most floating point operations are not checked.\n",
    "\n",
    "RecursionError\n",
    "\n",
    "This exception is derived from `RuntimeError`. It is raised when the\n",
    "interpreter detects that the maximum recursion depth (see\n",
    "`sys.getrecursionlimit`) is exceeded.\n",
    "\n",
    "3.5 Previously, a plain `RuntimeError` was raised.\n",
    "\n",
    "ReferenceError\n",
    "\n",
    "This exception is raised when a weak reference proxy, created by the\n",
    "`weakref.proxy` function, is used to access an attribute of the referent\n",
    "after it has been garbage collected. For more information on weak\n",
    "references, see the `weakref` module.\n",
    "\n",
    "RuntimeError\n",
    "\n",
    "Raised when an error is detected that doesn't fall in any of the other\n",
    "categories. The associated value is a string indicating what precisely\n",
    "went wrong.\n",
    "\n",
    "StopIteration\n",
    "\n",
    "Raised by built-in function `next` and an `iterator`'s\n",
    "`~iterator.__next__` method to signal that there are no further items\n",
    "produced by the iterator.\n",
    "\n",
    "The exception object has a single attribute `value`, which is given as\n",
    "an argument when constructing the exception, and defaults to `None`.\n",
    "\n",
    "When a `generator` or `coroutine` function returns, a new\n",
    "`StopIteration` instance is raised, and the value returned by the\n",
    "function is used as the `value` parameter to the constructor of the\n",
    "exception.\n",
    "\n",
    "If a generator code directly or indirectly raises `StopIteration`, it is\n",
    "converted into a `RuntimeError` (retaining the `StopIteration` as the\n",
    "new exception's cause).\n",
    "\n",
    "3.3 Added `value` attribute and the ability for generator functions to\n",
    "use it to return a value.\n",
    "\n",
    "3.5 Introduced the RuntimeError transformation via\n",
    "`from __future__ import generator_stop`, see `479`.\n",
    "\n",
    "3.7 Enable `479` for all code by default: a `StopIteration` error raised\n",
    "in a generator is transformed into a `RuntimeError`.\n",
    "\n",
    "StopAsyncIteration\n",
    "\n",
    "Must be raised by `__anext__` method of an `asynchronous iterator`\n",
    "object to stop the iteration.\n",
    "\n",
    "3.5\n",
    "\n",
    "SyntaxError(message, details)\n",
    "\n",
    "Raised when the parser encounters a syntax error. This may occur in an\n",
    "`import` statement, in a call to the built-in functions `compile`,\n",
    "`exec`, or `eval`, or when reading the initial script or standard input\n",
    "(also interactively).\n",
    "\n",
    "The `str` of the exception instance returns only the error message.\n",
    "Details is a tuple whose members are also available as separate\n",
    "attributes.\n",
    "\n",
    "filename\n",
    "\n",
    "The name of the file the syntax error occurred in.\n",
    "\n",
    "lineno\n",
    "\n",
    "Which line number in the file the error occurred in. This is 1-indexed:\n",
    "the first line in the file has a `lineno` of 1.\n",
    "\n",
    "offset\n",
    "\n",
    "The column in the line where the error occurred. This is 1-indexed: the\n",
    "first character in the line has an `offset` of 1.\n",
    "\n",
    "text\n",
    "\n",
    "The source code text involved in the error.\n",
    "\n",
    "end_lineno\n",
    "\n",
    "Which line number in the file the error occurred ends in. This is\n",
    "1-indexed: the first line in the file has a `lineno` of 1.\n",
    "\n",
    "end_offset\n",
    "\n",
    "The column in the end line where the error occurred finishes. This is\n",
    "1-indexed: the first character in the line has an `offset` of 1.\n",
    "\n",
    "For errors in f-string fields, the message is prefixed by \"f-string: \"\n",
    "and the offsets are offsets in a text constructed from the replacement\n",
    "expression. For example, compiling f'Bad {a b} field' results in this\n",
    "args attribute: ('f-string: ...', ('', 1, 2, '(a b)n', 1, 5)).\n",
    "\n",
    "3.10 Added the `end_lineno` and `end_offset` attributes.\n",
    "\n",
    "IndentationError\n",
    "\n",
    "Base class for syntax errors related to incorrect indentation. This is a\n",
    "subclass of `SyntaxError`.\n",
    "\n",
    "TabError\n",
    "\n",
    "Raised when indentation contains an inconsistent use of tabs and spaces.\n",
    "This is a subclass of `IndentationError`.\n",
    "\n",
    "SystemError\n",
    "\n",
    "Raised when the interpreter finds an internal error, but the situation\n",
    "does not look so serious to cause it to abandon all hope. The associated\n",
    "value is a string indicating what went wrong (in low-level terms).\n",
    "\n",
    "You should report this to the author or maintainer of your Python\n",
    "interpreter. Be sure to report the version of the Python interpreter\n",
    "(`sys.version`; it is also printed at the start of an interactive Python\n",
    "session), the exact error message (the exception's associated value) and\n",
    "if possible the source of the program that triggered the error.\n",
    "\n",
    "SystemExit\n",
    "\n",
    "This exception is raised by the `sys.exit` function. It inherits from\n",
    "`BaseException` instead of `Exception` so that it is not accidentally\n",
    "caught by code that catches `Exception`. This allows the exception to\n",
    "properly propagate up and cause the interpreter to exit. When it is not\n",
    "handled, the Python interpreter exits; no stack traceback is printed.\n",
    "The constructor accepts the same optional argument passed to `sys.exit`.\n",
    "If the value is an integer, it specifies the system exit status (passed\n",
    "to C's :c`exit` function); if it is `None`, the exit status is zero; if\n",
    "it has another type (such as a string), the object's value is printed\n",
    "and the exit status is one.\n",
    "\n",
    "A call to `sys.exit` is translated into an exception so that clean-up\n",
    "handlers (`finally` clauses of `try` statements) can be executed, and so\n",
    "that a debugger can execute a script without running the risk of losing\n",
    "control. The `os._exit` function can be used if it is absolutely\n",
    "positively necessary to exit immediately (for example, in the child\n",
    "process after a call to `os.fork`).\n",
    "\n",
    "code\n",
    "\n",
    "The exit status or error message that is passed to the constructor.\n",
    "(Defaults to `None`.)\n",
    "\n",
    "TypeError\n",
    "\n",
    "Raised when an operation or function is applied to an object of\n",
    "inappropriate type. The associated value is a string giving details\n",
    "about the type mismatch.\n",
    "\n",
    "This exception may be raised by user code to indicate that an attempted\n",
    "operation on an object is not supported, and is not meant to be. If an\n",
    "object is meant to support a given operation but has not yet provided an\n",
    "implementation, `NotImplementedError` is the proper exception to raise.\n",
    "\n",
    "Passing arguments of the wrong type (e.g. passing a `list` when an `int`\n",
    "is expected) should result in a `TypeError`, but passing arguments with\n",
    "the wrong value (e.g. a number outside expected boundaries) should\n",
    "result in a `ValueError`.\n",
    "\n",
    "UnboundLocalError\n",
    "\n",
    "Raised when a reference is made to a local variable in a function or\n",
    "method, but no value has been bound to that variable. This is a subclass\n",
    "of `NameError`.\n",
    "\n",
    "UnicodeError\n",
    "\n",
    "Raised when a Unicode-related encoding or decoding error occurs. It is a\n",
    "subclass of `ValueError`.\n",
    "\n",
    "`UnicodeError` has attributes that describe the encoding or decoding\n",
    "error. For example, `err.object[err.start:err.end]` gives the particular\n",
    "invalid input that the codec failed on.\n",
    "\n",
    "encoding\n",
    "\n",
    "The name of the encoding that raised the error.\n",
    "\n",
    "reason\n",
    "\n",
    "A string describing the specific codec error.\n",
    "\n",
    "object\n",
    "\n",
    "The object the codec was attempting to encode or decode.\n",
    "\n",
    "start\n",
    "\n",
    "The first index of invalid data in `object`.\n",
    "\n",
    "end\n",
    "\n",
    "The index after the last invalid data in `object`.\n",
    "\n",
    "UnicodeEncodeError\n",
    "\n",
    "Raised when a Unicode-related error occurs during encoding. It is a\n",
    "subclass of `UnicodeError`.\n",
    "\n",
    "UnicodeDecodeError\n",
    "\n",
    "Raised when a Unicode-related error occurs during decoding. It is a\n",
    "subclass of `UnicodeError`.\n",
    "\n",
    "UnicodeTranslateError\n",
    "\n",
    "Raised when a Unicode-related error occurs during translating. It is a\n",
    "subclass of `UnicodeError`.\n",
    "\n",
    "ValueError\n",
    "\n",
    "Raised when an operation or function receives an argument that has the\n",
    "right type but an inappropriate value, and the situation is not\n",
    "described by a more precise exception such as `IndexError`.\n",
    "\n",
    "ZeroDivisionError\n",
    "\n",
    "Raised when the second argument of a division or modulo operation is\n",
    "zero. The associated value is a string indicating the type of the\n",
    "operands and the operation.\n",
    "\n",
    "The following exceptions are kept for compatibility with previous\n",
    "versions; starting from Python 3.3, they are aliases of `OSError`.\n",
    "\n",
    "EnvironmentError\n",
    "\n",
    "IOError\n",
    "\n",
    "WindowsError\n",
    "\n",
    "Only available on Windows.\n",
    "\n",
    "### OS exceptions\n",
    "\n",
    "The following exceptions are subclasses of `OSError`, they get raised\n",
    "depending on the system error code.\n",
    "\n",
    "BlockingIOError\n",
    "\n",
    "Raised when an operation would block on an object (e.g. socket) set for\n",
    "non-blocking operation. Corresponds to :c`errno` :py`~errno.EAGAIN`,\n",
    ":py`~errno.EALREADY`, :py`~errno.EWOULDBLOCK` and\n",
    ":py`~errno.EINPROGRESS`.\n",
    "\n",
    "In addition to those of `OSError`, `BlockingIOError` can have one more\n",
    "attribute:\n",
    "\n",
    "characters_written\n",
    "\n",
    "An integer containing the number of characters written to the stream\n",
    "before it blocked. This attribute is available when using the buffered\n",
    "I/O classes from the `io` module.\n",
    "\n",
    "ChildProcessError\n",
    "\n",
    "Raised when an operation on a child process failed. Corresponds to\n",
    ":c`errno` :py`~errno.ECHILD`.\n",
    "\n",
    "ConnectionError\n",
    "\n",
    "A base class for connection-related issues.\n",
    "\n",
    "Subclasses are `BrokenPipeError`, `ConnectionAbortedError`,\n",
    "`ConnectionRefusedError` and `ConnectionResetError`.\n",
    "\n",
    "BrokenPipeError\n",
    "\n",
    "A subclass of `ConnectionError`, raised when trying to write on a pipe\n",
    "while the other end has been closed, or trying to write on a socket\n",
    "which has been shutdown for writing. Corresponds to :c`errno`\n",
    ":py`~errno.EPIPE` and :py`~errno.ESHUTDOWN`.\n",
    "\n",
    "ConnectionAbortedError\n",
    "\n",
    "A subclass of `ConnectionError`, raised when a connection attempt is\n",
    "aborted by the peer. Corresponds to :c`errno` :py`~errno.ECONNABORTED`.\n",
    "\n",
    "ConnectionRefusedError\n",
    "\n",
    "A subclass of `ConnectionError`, raised when a connection attempt is\n",
    "refused by the peer. Corresponds to :c`errno` :py`~errno.ECONNREFUSED`.\n",
    "\n",
    "ConnectionResetError\n",
    "\n",
    "A subclass of `ConnectionError`, raised when a connection is reset by\n",
    "the peer. Corresponds to :c`errno` :py`~errno.ECONNRESET`.\n",
    "\n",
    "FileExistsError\n",
    "\n",
    "Raised when trying to create a file or directory which already exists.\n",
    "Corresponds to :c`errno` :py`~errno.EEXIST`.\n",
    "\n",
    "FileNotFoundError\n",
    "\n",
    "Raised when a file or directory is requested but doesn't exist.\n",
    "Corresponds to :c`errno` :py`~errno.ENOENT`.\n",
    "\n",
    "InterruptedError\n",
    "\n",
    "Raised when a system call is interrupted by an incoming signal.\n",
    "Corresponds to :c`errno` :py`~errno.EINTR`.\n",
    "\n",
    "3.5 Python now retries system calls when a syscall is interrupted by a\n",
    "signal, except if the signal handler raises an exception (see `475` for\n",
    "the rationale), instead of raising `InterruptedError`.\n",
    "\n",
    "IsADirectoryError\n",
    "\n",
    "Raised when a file operation (such as `os.remove`) is requested on a\n",
    "directory. Corresponds to :c`errno` :py`~errno.EISDIR`.\n",
    "\n",
    "NotADirectoryError\n",
    "\n",
    "Raised when a directory operation (such as `os.listdir`) is requested on\n",
    "something which is not a directory. On most POSIX platforms, it may also\n",
    "be raised if an operation attempts to open or traverse a non-directory\n",
    "file as if it were a directory. Corresponds to :c`errno`\n",
    ":py`~errno.ENOTDIR`.\n",
    "\n",
    "PermissionError\n",
    "\n",
    "Raised when trying to run an operation without the adequate access\n",
    "rights - for example filesystem permissions. Corresponds to :c`errno`\n",
    ":py`~errno.EACCES` and :py`~errno.EPERM`.\n",
    "\n",
    "ProcessLookupError\n",
    "\n",
    "Raised when a given process doesn't exist. Corresponds to :c`errno`\n",
    ":py`~errno.ESRCH`.\n",
    "\n",
    "TimeoutError\n",
    "\n",
    "Raised when a system function timed out at the system level. Corresponds\n",
    "to :c`errno` :py`~errno.ETIMEDOUT`.\n",
    "\n",
    "3.3 All the above `OSError` subclasses were added.\n",
    "\n",
    "`3151` - Reworking the OS and IO exception hierarchy\n",
    "\n",
    "## Warnings\n",
    "\n",
    "The following exceptions are used as warning categories; see the\n",
    "`warning-categories` documentation for more details.\n",
    "\n",
    "Warning\n",
    "\n",
    "Base class for warning categories.\n",
    "\n",
    "UserWarning\n",
    "\n",
    "Base class for warnings generated by user code.\n",
    "\n",
    "DeprecationWarning\n",
    "\n",
    "Base class for warnings about deprecated features when those warnings\n",
    "are intended for other Python developers.\n",
    "\n",
    "Ignored by the default warning filters, except in the `__main__` module\n",
    "(`565`). Enabling the `Python Development Mode <devmode>` shows this\n",
    "warning.\n",
    "\n",
    "The deprecation policy is described in `387`.\n",
    "\n",
    "PendingDeprecationWarning\n",
    "\n",
    "Base class for warnings about features which are obsolete and expected\n",
    "to be deprecated in the future, but are not deprecated at the moment.\n",
    "\n",
    "This class is rarely used as emitting a warning about a possible\n",
    "upcoming deprecation is unusual, and `DeprecationWarning` is preferred\n",
    "for already active deprecations.\n",
    "\n",
    "Ignored by the default warning filters. Enabling the `Python\n",
    "Development Mode <devmode>` shows this warning.\n",
    "\n",
    "The deprecation policy is described in `387`.\n",
    "\n",
    "SyntaxWarning\n",
    "\n",
    "Base class for warnings about dubious syntax.\n",
    "\n",
    "RuntimeWarning\n",
    "\n",
    "Base class for warnings about dubious runtime behavior.\n",
    "\n",
    "FutureWarning\n",
    "\n",
    "Base class for warnings about deprecated features when those warnings\n",
    "are intended for end users of applications that are written in Python.\n",
    "\n",
    "ImportWarning\n",
    "\n",
    "Base class for warnings about probable mistakes in module imports.\n",
    "\n",
    "Ignored by the default warning filters. Enabling the `Python\n",
    "Development Mode <devmode>` shows this warning.\n",
    "\n",
    "UnicodeWarning\n",
    "\n",
    "Base class for warnings related to Unicode.\n",
    "\n",
    "EncodingWarning\n",
    "\n",
    "Base class for warnings related to encodings.\n",
    "\n",
    "See `io-encoding-warning` for details.\n",
    "\n",
    "3.10\n",
    "\n",
    "BytesWarning\n",
    "\n",
    "Base class for warnings related to `bytes` and `bytearray`.\n",
    "\n",
    "ResourceWarning\n",
    "\n",
    "Base class for warnings related to resource usage.\n",
    "\n",
    "Ignored by the default warning filters. Enabling the `Python\n",
    "Development Mode <devmode>` shows this warning.\n",
    "\n",
    "3.2\n",
    "\n",
    "## Exception groups\n",
    "\n",
    "The following are used when it is necessary to raise multiple unrelated\n",
    "exceptions. They are part of the exception hierarchy so they can be\n",
    "handled with `except` like all other exceptions. In addition, they are\n",
    "recognised by `except*<except_star>`, which matches their subgroups\n",
    "based on the types of the contained exceptions.\n",
    "\n",
    "ExceptionGroup(msg, excs)\n",
    "\n",
    "BaseExceptionGroup(msg, excs)\n",
    "\n",
    "Both of these exception types wrap the exceptions in the sequence\n",
    "`excs`. The `msg` parameter must be a string. The difference between the\n",
    "two classes is that `BaseExceptionGroup` extends `BaseException` and it\n",
    "can wrap any exception, while `ExceptionGroup` extends `Exception` and\n",
    "it can only wrap subclasses of `Exception`. This design is so that\n",
    "`except Exception` catches an `ExceptionGroup` but not\n",
    "`BaseExceptionGroup`.\n",
    "\n",
    "The `BaseExceptionGroup` constructor returns an `ExceptionGroup` rather\n",
    "than a `BaseExceptionGroup` if all contained exceptions are `Exception`\n",
    "instances, so it can be used to make the selection automatic. The\n",
    "`ExceptionGroup` constructor, on the other hand, raises a `TypeError` if\n",
    "any contained exception is not an `Exception` subclass.\n",
    "\n",
    "message\n",
    "\n",
    "The `msg` argument to the constructor. This is a read-only attribute.\n",
    "\n",
    "exceptions\n",
    "\n",
    "A tuple of the exceptions in the `excs` sequence given to the\n",
    "constructor. This is a read-only attribute.\n",
    "\n",
    "subgroup(condition)\n",
    "\n",
    "Returns an exception group that contains only the exceptions from the\n",
    "current group that match *condition*, or `None` if the result is empty.\n",
    "\n",
    "The condition can be either a function that accepts an exception and\n",
    "returns true for those that should be in the subgroup, or it can be an\n",
    "exception type or a tuple of exception types, which is used to check for\n",
    "a match using the same check that is used in an `except` clause.\n",
    "\n",
    "The nesting structure of the current exception is preserved in the\n",
    "result, as are the values of its `message`, `__traceback__`,\n",
    "`__cause__`, `__context__` and `__notes__` fields. Empty nested groups\n",
    "are omitted from the result.\n",
    "\n",
    "The condition is checked for all exceptions in the nested exception\n",
    "group, including the top-level and any nested exception groups. If the\n",
    "condition is true for such an exception group, it is included in the\n",
    "result in full.\n",
    "\n",
    "split(condition)\n",
    "\n",
    "Like `subgroup`, but returns the pair `(match, rest)` where `match` is\n",
    "`subgroup(condition)` and `rest` is the remaining non-matching part.\n",
    "\n",
    "derive(excs)\n",
    "\n",
    "Returns an exception group with the same `message`, `__traceback__`,\n",
    "`__cause__`, `__context__` and `__notes__` but which wraps the\n",
    "exceptions in `excs`.\n",
    "\n",
    "This method is used by `subgroup` and `split`. A subclass needs to\n",
    "override it in order to make `subgroup` and `split` return instances of\n",
    "the subclass rather than `ExceptionGroup`. :\n",
    "\n",
    "    >>> class MyGroup(ExceptionGroup):\n",
    "    ...     def derive(self, exc):\n",
    "    ...         return MyGroup(self.message, exc)\n",
    "    ...\n",
    "    >>> MyGroup(\"eg\", [ValueError(1), TypeError(2)]).split(TypeError)\n",
    "    (MyGroup('eg', [TypeError(2)]), MyGroup('eg', [ValueError(1)]))\n",
    "\n",
    "Note that `BaseExceptionGroup` defines `__new__`, so subclasses that\n",
    "need a different constructor signature need to override that rather than\n",
    "`__init__`. For example, the following defines an exception group\n",
    "subclass which accepts an exit_code and and constructs the group's\n",
    "message from it. :\n",
    "\n",
    "    class Errors(ExceptionGroup):\n",
    "       def __new__(cls, errors, exit_code):\n",
    "          self = super().__new__(Errors, f\"exit code: {exit_code}\", errors)\n",
    "          self.exit_code = exit_code\n",
    "          return self\n",
    "\n",
    "       def derive(self, excs):\n",
    "          return Errors(excs, self.exit_code)\n",
    "\n",
    "3.11\n",
    "\n",
    "## Exception hierarchy\n",
    "\n",
    "The class hierarchy for built-in exceptions is:\n",
    "\n",
    "../../Lib/test/exception_hierarchy.txt"
   ],
   "id": "181a79c4-ca49-4f79-b806-1cc0a791b28a"
  }
 ],
 "nbformat": 4,
 "nbformat_minor": 5,
 "metadata": {}
}
